require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.lspconfig")
require("core.plugin_config.which-key")
require("core.plugin_config.todo-comments")
require("core.plugin_config.gitsigns")
-- require("core.plugin_config.dbtpal")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.none-ls")
require("core.plugin_config.completions")
require("core.plugin_config.lspconfig")
require("core.plugin_config.theme")
require("core.plugin_config.autopairs")
require("core.plugin_config.dap")
require("core.plugin_config.codeium")
