#!/bin/bash
# Switch to docked mode (external monitors only)
if [ "$1" = "docked" ]; then
  hyprctl keyword monitor "eDP-1, disable"
  hyprctl keyword monitor "DVI-I-1,1920x1080@60.0,3840x0,1.0"
  hyprctl keyword monitor "DVI-I-1,transform,1"
  hyprctl keyword monitor "DVI-I-2,1920x1080@60.0,1920x341,1.0"
elif [ "$1" = "docked2" ]; then
  hyprctl keyword monitor "eDP-1, disable"
  hyprctl keyword monitor "DVI-I-2,1920x1080@60.0,3840x0,1.0"
  hyprctl keyword monitor "DVI-I-2,transform,1"
  hyprctl keyword monitor "DVI-I-1,1920x1080@60.0,1920x341,1.0"
# Switch to mobile mode (laptop display only)
elif [ "$1" = "mobile" ]; then
  hyprctl keyword monitor "eDP-1,1920x1080@60.05,0x341,1.0"
  hyprctl keyword monitor "DVI-I-1, disable"
  hyprctl keyword monitor "DVI-I-2, disable"
fi

# Generated by nwg-displays on 2025-11-08 at 10:40:11. Do not edit manually.
