require("plugins.config.nvim-tree")
require("plugins.config.autopairs")
require("plugins.config.codeium")
require("plugins.config.completions")
require("plugins.config.dap")
-- require("plugins.config.dbtpal")
require("plugins.config.git-worktree")
require("plugins.config.gitsigns")
require("plugins.config.harpoon")
require("plugins.config.indent-blankline")
require("plugins.config.lspconfig")
require("plugins.config.lualine")
require("plugins.config.none-ls")
-- require("plugins.config.notify")
require("plugins.config.snacks")
require("plugins.config.telescope")
require("plugins.config.todo-comments")
require("plugins.config.treesitter")
require("plugins.config.twilight")
require("plugins.config.which-key")
require("plugins.config.lspsaga")
require("plugins.config.obsidian")
require("plugins.config.mini")
