-- nvim-treesitter (main branch) no longer uses require("nvim-treesitter.configs").setup()
-- Configuration is now handled via opts in the lazy.nvim plugin spec (lua/plugins/lazy.lua)
-- Highlight and indent are built into Neovim 0.12+ and enabled automatically
