-- Monitor configuration
-- Migrated from monitors.conf (generated by nwg-displays)

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@143.98",
    position = "0x0",
    scale = 1.0,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x-300",
    scale = 1.0,
    transform = 1,
})
