vim.keymap.set('n', '<leader>h', ':nohlsearch<cr>')
vim.keymap.set('n', '<leader>w', ':w<cr>')
vim.keymap.set('n', '<leader>q', ':q<cr>')
vim.keymap.set('n', '<leader>qq', ':q!<cr>')
vim.keymap.set('n', '<leader>j', ':bn<cr>')
vim.keymap.set('n', '<leader>k', ':bp<cr>')
