prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    type: null
  - title: Needs My Review
    filters: is:open review-requested:@me
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null
  - title: All Open
    filters: is:open
    type: null
  - title: All Closed
    filters: is:closed
    type: null
  - title: Axon Open
    filters: |
      is:open 
      repo:Branching-Minds/datalake-pipelines 
      repo:Branching-Minds/data-workflows 
      repo:Branching-Minds/databricks-data-workflows
    type: null
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: All Open
    filters: is:open
    type: null
  - title: All Closed
    filters: is:closed
    type: null
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 80
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: false
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit

  prs:
    - key: O
      builtin: checkout
    # - key: m
    #   command: gh pr merge --admin --repo {{.RepoName}} {{.PrNumber}}
    - key: M
      name: Auto-Merge
      command: gh pr merge --auto --squash --delete-branch --repo {{.RepoName}} {{.PrNumber}}
    - key: U
      name: Update Branch
      command: gh api repos/{{.RepoName}}/pulls/{{.PrNumber}}/update-branch -X PUT
    - key: C
      name: code review
      command: >
        tmux new-window -c {{.RepoPath}} ' nvim -c ":silent Octo pr edit {{.PrNumber}}" '

    - key: a
      name: lazygit add
      command: >
        cd {{.RepoPath}} && git add -A && lazygit

    - key: v
      name: approve
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

  issues: []
  branches: []
repoPaths:
  Branching-Minds/datalake-pipelines: ~/brm_repos/datalake-pipelines-workdir/pr_review
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
